services:
  database:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  rabbitMq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - "5672:5672"

volumes:
  db: